sonar.projectKey=hytsnbr_shiny-colors-cd-info-api
sonar.organization=hytsnbr

# 解析の起点をプロジェクトルート（.）に変更します
# これにより、LCOV内の "src/..." というパスと正確に一致します
sonar.sources=.
sonar.inclusions=src/**/*.ts
sonar.exclusions=src/tests/**/*.ts, coverage_result/**

# テストコードの設定
sonar.tests=.
sonar.test.inclusions=src/tests/**/*.ts

# カバレッジレポートのパス
sonar.javascript.lcov.reportPaths=lcov.info

sonar.language=ts
sonar.sourceEncoding=UTF-8
