# プロジェクトの一意識別子
sonar.projectKey=hytsnbr_shiny-colors-cd-info-api
sonar.organization=hytsnbr

# 解析対象のソースコード
sonar.sources=.
# テストファイルは解析（バグ検知）から除外
sonar.exclusions=coverage_result/**

# カバレッジレポートのパス（重要！）
sonar.javascript.lcov.reportPaths=coverage_result/lcov.info

# TypeScriptとして認識させる
sonar.language=ts
sonar.sourceEncoding=UTF-8
