name: Dependency Cache Update

on: 
  push:
    branches:
      - dependency/*

jobs:
  dependency-cache-update:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LABEL_NAME: "依存関係キャッシュ更新"

    steps:
      - name: set Env value
        env:
          TZ: "Asia/Tokyo" # タイムゾーン指定
        run: |
          echo "process_date=`date '+%Y-%m-%d %H:%M:%S'`" >> "$GITHUB_ENV"

      - name: Checkout Repo
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Deno Setup
        uses: denoland/setup-deno@v1.2.0

      - name: Run cached
        run: deno task cached

      - name: Diff
        id: diff
        run: git diff --name-only --exit-code
        continue-on-error: true

      - name: Commit & Push
        id: commit_push
        if: steps.diff.outcome == 'failure'
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "chore(dependency cache): Cache Updated at ${{ env.process_date }}"
          git push --set-upstream origin ${{ env.branch_name }}
